import type { ChangelogEntry } from "../types.js";

const entry: ChangelogEntry = {
  date: "2026-09-12",
  title: "Brazil, Argentina, Mexico and the United States",
  items: [
    "New saves now include **four leagues from the Americas**: Brazil, Argentina, Mexico and the United States. Each has three divisions and its own fictional clubs, and the squads are drawn from each league's real nationality mix, so Liga MX is full of Argentines and Uruguayans and MLS has a big Canadian and South American contingent.",
    "They're built the way the real leagues work. **Brazil** is a straight 38-round table with four up and four down. **Argentina** has its real 30 clubs in **two zones of 15**, over a second division of 36 in two zones of 18, and promotes and relegates two. **Mexico and the US are closed**: nobody goes up or down. The US has its real 30 clubs in an **Eastern and a Western Conference**, placed by geography, and plays MLS's 34 games: your own conference twice, a rival from the other conference home and away, and four more cross-conference games. Its second division has 30 clubs in two conferences as well. Standings shows each conference or zone as its own table, with an overall table beside them.",
    "Some leagues now decide their champion in a **title playoff**. In **Mexico** the top eight play the Liguilla over two legs a round, with the real tiebreaker: a quarter-final or semi-final that's level on aggregate goes to the club that finished higher, and only the final goes to extra time and penalties. In the **US** the top nine in each conference go in: a wild card, a best-of-three first round, then one-off games up to a final between the two conference champions. In **Argentina** the top eight in each zone meet across the zones in a round of 16, with level games going straight to penalties until the final. The table still decides prize money, continental places and what your board thinks of you. There's a new **Title Playoffs** page for the brackets.",
    "Playoffs are now **played a round at a time** instead of all at once when the season ends. Once the last matchday is done the brackets are drawn, and the Dashboard gives you a button for each round, title playoffs and promotion playoffs together. The rounds line up so every final is on the same click, and the offseason and your board's verdict wait until they're all played. If your club is in one, **Sim through the playoffs** stops before each of your rounds so you can set your lineup.",
    "The American clubs have their own continental competition, the **Americas Cup**. The top four in each of the four top flights qualify, and a domestic cup winner can take one of those places. European and American clubs never meet in each other's competitions, but the Continental Cup winner now plays the Americas Cup winner in a new **Intercontinental Cup** in the preseason.",
    "The world awards and the GOAT board stay about Europe. Anything done at a club in the Americas counts for a quarter of the same thing in Europe, so a great career over there won't win the Ballon d'Or or top the all-time lists. The Americas get their **own awards** instead: a Player of the Year, a Goalkeeper and a Defender of the Year, and a Team of the Year, on a new Americas tab on the Awards page.",
    "**Power Rankings** and the **Frivolities** boards (GOAT, Records, All-Time Leaders and Club Records) have a Europe / Americas switch, so each continent gets its own list instead of one ranking that mixes clubs that never play each other. The Frivolities boards also have a **Both** option if you want everyone on one list, where Americas accomplishments still count for a quarter.",
    "Existing saves keep the world they were made with. The new leagues only appear when you start a new save, and you can still switch any country off on the new league screen. Countries there are now grouped under Europe and the Americas, and World setup has a checkbox on each heading to switch a whole continent on or off at once.",
  ],
};

export default entry;
